import thor from "../../assets/dogs/dog2_0-image.jpg";
import luna from "../../assets/dogs/dog3_0-image.jpg";
import max from "../../assets/dogs/dog4_0-image.jpg";
import barao from "../../assets/dogs/dog5_0-image.jpg";
import rex from "../../assets/dogs/dog6_0-image.jpg";
import mia from "../../assets/cats/cat1_0-image.jpg";
import simba from "../../assets/cats/cat2_0-image.jpg";
import nala from "../../assets/cats/cat3_0-image.jpg";
import gizmo from "../../assets/cats/cat4_0-image.jpg";
import frajola from "../../assets/cats/cat5_0-image.jpg";
import amora from "../../assets/cats/cat6_0-image.jpg";

// Doadores de exemplo da página de busca, enquanto o site não está ligado à
// API. É o resumo que a busca precisa de cada animal: o que decide a escolha
// (espécie, tipo, porte, bairro, validação). Cidade e bairro são os do tutor.
//
// São exemplos independentes dos animais dos perfis (dados/exemplos/animais):
// um "Thor" aqui não é o mesmo Thor de lá. Com a API, as duas telas passam a
// ler o mesmo cadastro.

const doador = (dados) => ({ cidade: "Viçosa - MG", ...dados });

export const DOADORES = [
  doador({
    id: 1,
    codigo: "A1B2C3",
    nome: "Thor",
    tutorCodigo: "T7X9K2",
    foto: thor,
    especie: "CAO",
    raca: "Golden Retriever",
    dataNascimento: "2022-04-12",
    tipoSanguineo: "DEA 1.1+",
    pesoKg: 32,
    bairro: "Centro",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 2,
    codigo: "D4E5F6",
    nome: "Luna",
    tutorCodigo: "T3M8P1",
    foto: luna,
    especie: "CAO",
    raca: "Labrador",
    dataNascimento: "2023-02-18",
    tipoSanguineo: "DEA 4",
    pesoKg: 28,
    bairro: "Santa Clara",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 3,
    codigo: "G7H8I9",
    nome: "Max",
    tutorCodigo: "T5K2W7",
    foto: max,
    especie: "CAO",
    raca: "Beagle",
    dataNascimento: "2021-06-30",
    tipoSanguineo: null,
    pesoKg: 16,
    bairro: "Ramos",
    disponivel: false,
    validado: false,
  }),
  doador({
    id: 4,
    codigo: "J1K2L3",
    nome: "Barão",
    tutorCodigo: "T9R4B6",
    foto: barao,
    especie: "CAO",
    raca: "Bernese",
    dataNascimento: "2020-03-22",
    tipoSanguineo: "DEA 1.1 Universal",
    pesoKg: 45,
    bairro: "Nova Viçosa",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 5,
    codigo: "M4N5O6",
    nome: "Rex",
    tutorCodigo: "T2P7X3",
    foto: rex,
    especie: "CAO",
    raca: "Pastor Alemão",
    dataNascimento: "2024-01-15",
    tipoSanguineo: "DEA 1.1-",
    pesoKg: 38,
    bairro: "Belvedere",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 6,
    codigo: "P7Q8R9",
    nome: "Bolt",
    tutorCodigo: "T6W1M4",
    foto: null,
    especie: "CAO",
    raca: "Dálmata",
    dataNascimento: "2022-07-09",
    tipoSanguineo: null,
    pesoKg: 30,
    bairro: "Inconfidência",
    disponivel: true,
    validado: false,
  }),
  doador({
    id: 7,
    codigo: "S1T2U3",
    nome: "Mia",
    tutorCodigo: "T8B3K9",
    foto: mia,
    especie: "GATO",
    raca: null,
    dataNascimento: "2023-05-02",
    tipoSanguineo: "Tipo A",
    pesoKg: 4.2,
    bairro: "Centro",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 8,
    codigo: "V4W5X6",
    nome: "Simba",
    tutorCodigo: "T1X6P2",
    foto: simba,
    especie: "GATO",
    raca: "Maine Coon",
    dataNascimento: "2022-03-27",
    tipoSanguineo: "Tipo B",
    pesoKg: 6.1,
    bairro: "Nova Viçosa",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 9,
    codigo: "Y7Z8A9",
    nome: "Nala",
    tutorCodigo: "T4M9R5",
    foto: nala,
    especie: "GATO",
    raca: "Persa",
    dataNascimento: "2024-04-11",
    tipoSanguineo: null,
    pesoKg: 4.8,
    bairro: "Ramos",
    disponivel: false,
    validado: false,
  }),
  doador({
    id: 10,
    codigo: "B1C2D3",
    nome: "Gizmo",
    tutorCodigo: "T7K4W8",
    foto: gizmo,
    especie: "GATO",
    raca: null,
    dataNascimento: "2021-01-19",
    tipoSanguineo: "Tipo A",
    pesoKg: 5.3,
    bairro: "Santa Clara",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 11,
    codigo: "E4F5G6",
    nome: "Frajola",
    tutorCodigo: "T2R8M1",
    foto: frajola,
    especie: "GATO",
    raca: null,
    dataNascimento: "2023-08-06",
    tipoSanguineo: "Tipo A",
    pesoKg: 4.5,
    bairro: "Centro",
    disponivel: true,
    validado: true,
  }),
  doador({
    id: 12,
    codigo: "H7I8J9",
    nome: "Amora",
    tutorCodigo: "T5W2K6",
    foto: amora,
    especie: "GATO",
    raca: "Siamês",
    dataNascimento: "2022-09-14",
    tipoSanguineo: null,
    pesoKg: 3.9,
    cidade: "Teixeiras - MG",
    bairro: "Centro",
    disponivel: true,
    validado: false,
  }),
];
